name: Deploy Readify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/Readify

            echo "Pull latest code..."
            git pull origin main

            echo "Install backend packages..."
            cd Backend
            npm install

            echo "Restart backend..."
            pm2 restart readify-backend

            cd ..

            echo "Deploy frontend..."
            sudo rm -rf /var/www/readify/*

            sudo cp -r /home/ubuntu/Readify/Frontend/User/* /var/www/readify/

            # Copy apiConfig.js
            sudo cp /home/ubuntu/Readify/Frontend/apiConfig.js /var/www/readify/

            echo "Reload nginx..."
            sudo systemctl reload nginx

            echo "Deployment completed!"